---
apiVersion: v1
kind: Pod
metadata:
 - name: jenkins-Pod
   labels:
    type: ci-cd tools
    authour: intelliqit
spec:
 containers:
  - name: jenkins
    image: jenkins/jenkins
    ports: 
     - containerPorts: 8080
       hostsPorts: 80
...